apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: neptune-mysql-secret
  namespace: neptune
spec:
  encryptedData:
    MYSQL_DATABASE: AgCmHpLEU60Qd5w0DQj1V4BiU5inJ1bCuUwgnmHSPNIf0/hn+0yCTz+gdn6yJWOa5Fhi9eJtDvyjYgMAnXq1n/tdNrdBEvYD4hbFhf1xE/NthfchFMcALunfeaaE5kEvsKX1m7bG53Te6swYBVNK2a10ZZtTK70oMqwgioJqqkNdri2FdLlwC00wYQBfXdgJ21nkt7uTNY3ObL/XbV8k+z2Ksc1x612LBlBkNmzQRcHVO2hoIcqLao8Ay8JA8sQr1tCvBJLtUMRcCcaCB4FVUDbsY3amtmA2IUxgSyZOo1dq1g2r6pY62tnntJf++wkK1Yp6V0fzmTRDrI68dp0WPIzCSLYeoZDr4D87Dj8pEmJGr+rJWukEwIIuD6/AfU8MIZDcvmtG+Dmn0ujBuCiWTdvvwxEyUMvNchpibspj8t0LvRpRGyUzkvfTiMa/LsFfdU4e5P2uO3aC27BU5KLa0GfMGq00xjC2S6m1NCiJf9S6VOLHc2zSGUZbFHlVCYJ0kIrLuv70sGl08abWrcJuyS2L0mlHMJk6KIel78cmPFfutEBOcohDS3oHGEIwXKUdPmMaF/U01B5QTtABlcTyOD1ljZ3n6q4rrS39SBhIExY3P+Xm0c7B5DbdFvcgmsSH59m0UwWEUhJmJ24TZrI3W1uKCdDMzzznsaE+vfjP/ylcj3eMuj+RGUnRbLww+e4Y80q1sFRtguAw
    MYSQL_PASSWORD: AgBACAzPKtmZbUisiOD0BthTmbhk6QNtHRYCa5C3P7QZ4/fOFTprF+mmu6Op3/NZKbBqc5txnWRS0ZjwiufgzbBExl9BRcf9lpl2OKuw9uiZnyKX5U9DgMU6tYc65eyIQggp6KaMevfk1FIRjhwPjJ+C9R+259Y7fayrI1fEIyWjf365aZFWjjQHbgPUBBbZ59QZ8BFSkIJBB/WxiOaDm66wc5iFwlXUhkv6KNJCLinjaHhdzAM4pkzwfj26zSxdEdYzjE5r7kpYfr7iPAtCU5/9fyZ9Ru5cAy6dXrxEGWQOc3oT18gTwuDNSBunsiXCQfANlTySe3nrxsZ3dArX/DjDMEmPIqNiAAbYPQE139DzQ0gDod9jzsMbScqOHAOMOM2RzdCV75BGPPBL/G6NTi2mBLWFf3Lna8SWRkwXJcqnSJZDA5q5oOMzzNDhlkqKXXURt9YTzIpt3g4qUmYamb4JUSFLwT30Rg2aUAzetQfdiGij8bkXVFRi2vjiI0VKKtL6v13clNSISOSwkaHkCJ2wLHmyEuVk3rJyTkB8vQzJhkQMkEPpI4c31VFUXMmaLY0xaRdIHWTaH3oN/3pj+X7yaI5AP78DF6s6C6h8gNkXYvqJy5BzLtAnj5RfP8hIkTqs/ZSW1AgpUl4VaIRc1UINyptIZX2iwxnFybUHvqNGsMOKfmTMqTJ2rFwYBsqBhZZGJ9FO8QKN
    MYSQL_ROOT_PASSWORD: AgBlPtCsCSRKl014Kz5G5WOqE7L2LOfBUKbsGGbza8zzJqQNjAf0pVu4+zJM98R/5NF7G874KuMSHtTd6IZ69g/TcmtJY1jVUuFnOVYMLUScI7Lk/6g8i/5PaTP5oLLXWGo3ZfB4wgL+9jM7TRzhAVDrPffFNxxKq+GHZhyr8FT7USBr9sH24EcWsSdfasjWDMfIYsQVXHaX+W3hbdGWesAUna0lptL6ZTbkT0LqjCFF0R6PAu64sW75O77kiL4+OdGR9MM35ZQiampOcaREYpfcvdzZoZOtEUjrOOGnUwDpfkNrIMftIiAw5fNAw5JbmC8EmB6Q02OFZBxJwTQF8ScIn/rappwTPDm3GchrcgzhRXUIWDgO9xA9iyJWFjLxh5qhrQ3PPHBdHAwxDJeA04+HQRBTrl7pQTUooq3tQV9Lv2Sx14lZh9XYR83AHlW7s3lqUUV96LTrrvTcIls/HYUFutwSYzwxBP9f6wTS47lp+wq4oOCG0MtUR7846hqi9blTgwBwto7OP0EtOYLfL1owhylS2tld/JWH7EuQ1qt7OVwGv56dJwdUuJ3L/TURb/rRp41jvqJyTplME8wPwUWjafS3OKaNqrHKbpapAD87HRDktNPsyQrd+aJVCYnBLVN3k5Zk+NbGcZAMJREku+FwU8VsIgeF/loytVMD6/RTSKDTo1B3d/jU55zgO8mgzl0vzRHH
    MYSQL_USER: AgAQlGq+7ewzPEL4vJZRY9vs6tnayvGnjfSr2r4o8PWudcHlibZakEGhJtbOo8tnuqFQmdT3pXah4npHc48toZb4lgoiRRx2TYU3qr8FCiWjWKYpmorWMLUnv/KMtwm//YzY38NegmV4LlJmgsZvPUUTfQ/grOuKUEatAx7xtG8+mjToF3hIym2dQt1pLszY3B5jeiTkTjz9tWcaOlOG1MQQNxwGH6JvJn5IoaKGxytQcdfHf9363vdD1akOkOddQ+BE5RdXpASdJUgEclnSw5kIBvmgBpoQsMm622zpVqzg5Yhq6Bq0b+3uBgDgeO8oB+Ezime/QyjJIv4PnF+AFXV8Z7ySQmepzvFo2vRbGMH63y5CLUzpGOetQ/lSetgn4kVYoAl/0Sa9v8hzFXcQXRMcLdZ+XsOaoNI08QUaEIYBXTPEw+CbBAbiteERW3B5J4uwT7G+D1B2I0a6R0TIlTqqMY3D03bk+VvhivAFGg8Db3+zzbjkB3wPlomNT56//wvuM4q0evQJVIj+Gj/UYYhv+o5urJboAlP6/Y9wupUQ3KrRFaIyUlV58sJ7RLDGm6WPbBdO0U+YgKYuBID888pPjx8ijYahzO5ojNdIgmWMrqAz7DjBDxiXXuhx+oaH7fgXvX4bFZjGp0WnG7LsJZxiw55eyJwC0yfRh8T6tI4LnI4lHZgRWxnIkyf+PwX97GZtB4bd8AAM
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/created-by: ssbostan
        app.kubernetes.io/name: mysql
        app.kubernetes.io/part-of: neptune
      name: neptune-mysql-secret
      namespace: neptune
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: neptune-neptune-secret
  namespace: neptune
spec:
  encryptedData:
    NEPTUNE_API_DATABASE_URI: AgCpn8XyZKPtTuAxYN/RqE6SEufYz7OrZuutuaqIrCFVq16AePf7l7JHqpQugohGmzzXMCvarqF146Ufmn/XhGQ5pRFXq+n33RQS0YEefWCi/MRGv6rW4SzWaRdl8zn+tmRRSWMAzPSVP9tx8KYRweA93ZhbAf734m8+/i54XAWhvwjsQraqRz9XPKNnVky9uBHFijYYqYqqyZlbtIIJhDOmkMDW0kRLoee9yVbFb/AVvYDpkQX8uHFL/rrvraTOrIkFAe/rTVFUyN56MQZBJ/n4ZsqyGW18c4bijbn+ouLcMvpVvWG086s4YqmGR8pKZJuHn5L+e9AJuHfClNnIMLU8sJZOF372S3QAaEvpTU9U+pOXyY/9iBfbZ+zDWaHK+dGtlJYtptNrLPdOEFruYirGgwG5ckOVu7yNzRQVdbsoy/pKU8KU6cHXeimxV6A/mdAl6oDZCZxn8JueJVDDluBQEFjSonEFQfiRKNXIqoSRQSGTYuaClKYbGSQMEYv8CL8pqn+Y2ER8T2zGgKppSoB1dh2PcP72qmqJfvQHjZlCp3lQZr3XdxwB3oOZqteeDd+cLZmtwH2xGeFEZFqRtEPI2HFp+583P/i1lm/+gpKOPai3d9jB5WQwGFyvHYgUo2GoczRlvqSSD63Wtz4HH0Iz7BTUAFufgWREUqegT9Z0u1URPK8kxoulngB4Tdq0N2gg/MOmb9pCldKdsLcMMvU5Lc2c357wGBhDH2erUfAUHfC0OUsiyKfoXgkFK0I85f09/1tP96j8Q1ta
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/created-by: ssbostan
        app.kubernetes.io/name: neptune
        app.kubernetes.io/part-of: neptune
      name: neptune-neptune-secret
      namespace: neptune
