{{- if not .Values.neptune.sealedSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  NEPTUNE_API_DATABASE_URI: {{ printf "mysql+pymysql://%s:%s@%s:3306/%s" .Values.mysql.secret.mysqlUser .Values.mysql.secret.mysqlPassword ( printf "%s-%s" .Release.Name "mysql" | trunc 63 | trimSuffix "-" ) .Values.mysql.secret.mysqlDatabase | b64enc }}
{{- end -}}
