{{- if not .Values.sealedSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ b64enc .Values.secret.mysqlRootPassword }}
  MYSQL_DATABASE: {{ b64enc .Values.secret.mysqlDatabase }}
  MYSQL_USER: {{ b64enc .Values.secret.mysqlUser }}
  MYSQL_PASSWORD: {{ b64enc .Values.secret.mysqlPassword }}
{{- end -}}
